name: Remove Duplicates and Merge Files

on:
  push:
    branches:
      - main

jobs:
  process-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Remove duplicates from Blocklist.txt
        run: sort Blocklist.txt | uniq > Blocklist_temp.txt && mv Blocklist_temp.txt Blocklist.txt
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Blocklist.txt
          git commit -m "Remove duplicates and merge files" || echo "No changes to commit"
          git push origin main
